import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProviderWrapper } from "@/components/Providers/ClerkProviderWrapper";
import { ThemeProvider } from "@/components/Providers/ThemeProvider";

import { Toaster } from "sonner";
import { ModalProvider } from "@/components/Providers/ModalProvider";
import { EdgeStoreProvider } from "@/lib/edgestore";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NoteScape",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/logo.png",
      href: "/logo.png",
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProviderWrapper>
          <EdgeStoreProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange storageKey="notescape-theme">
              <Toaster position="bottom-right" />
              <ModalProvider />
              {children}
            </ThemeProvider>
          </EdgeStoreProvider>
        </ClerkProviderWrapper>
      </body>
    </html>
  );
}
